import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import authRoutes from './modules/auth/auth.routes.js';
import usersRoutes from './modules/users/users.routes.js';
import patientsRoutes from './modules/patients/patients.routes.js';
import doctorsRoutes from './modules/doctors/doctors.routes.js';
import healthWorkersRoutes from './modules/health-workers/healthWorkers.routes.js';
import appointmentsRoutes from './modules/appointments/appointments.routes.js';
import referralsRoutes from './modules/referrals/referrals.routes.js';
import requestsRoutes from './modules/requests/requests.routes.js';
import reportsRoutes from './modules/reports/reports.routes.js';
import { notFound, errorHandler } from './middleware/error.middleware.js';
const app=express();
app.disable('x-powered-by'); app.use(helmet());
app.use(cors({origin:process.env.FRONTEND_URL||'http://localhost:5173'}));
app.use(express.json({limit:'1mb'}));
app.get('/api/health',(_req,res)=>res.json({status:'ok',service:'SwasthyaConnect API'}));
app.use('/api/auth',authRoutes);app.use('/api/users',usersRoutes);app.use('/api/patients',patientsRoutes);app.use('/api/doctors',doctorsRoutes);app.use('/api/health-workers',healthWorkersRoutes);app.use('/api/appointments',appointmentsRoutes);app.use('/api/referrals',referralsRoutes);app.use('/api/requests',requestsRoutes);app.use('/api/reports',reportsRoutes);
app.use(notFound);app.use(errorHandler);
export default app;
